# apiVersion: v1
# kind: Pod
# metadata:
#   name: alpine
#   namespace: alpine
# spec:
#   containers:
#   - image: alpine:3.2
#     command:
#       - /bin/sh
#       - "-c"
#       - "sleep 60m"
#     imagePullPolicy: IfNotPresent
#     name: alpine
#   restartPolicy: Never

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: alpine
  name: alpine
  namespace: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      run: alpine
  strategy: {}
  template:
    metadata:
      labels:
        run: alpine
    spec:
      containers:
      - image: alpine:latest
        command:
          - /bin/sh
          - "-c"
          - "sleep 1m"
        imagePullPolicy: IfNotPresent
        name: alpine
