apiVersion: v1
kind: Namespace
metadata:
  name: demo-0116
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: demo-0116
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Never
