kind: Deployment
apiVersion: apps/v1
metadata:
  name: busybox
  namespace: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: demo-busybox
  template:
    metadata:
      labels:
        deploy: demo-busybox
    spec:
      containers:
        - name: busybox
          image: busybox:latest