kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-world
spec:
  replicas: 1
  strategy: Recreate
  selector:
    matchLabels:
      deploy: demo-deploy
  template:
    metadata:
      labels:
        deploy: demo-deploy
    spec:
      containers:
        - name: hello-world
          image: hello-world:latest