apiVersion: v1
kind: Namespace
metadata:
  name: demo-L4-0109
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: demo-L4-0109
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Never
