apiVersion: v1
kind: Namespace
metadata:
  name: demo-gitops2
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-gitops3
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-gitops
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: demo-gitops2
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox2
  restartPolicy: Never
